app = "ft-doss-backend"
primary_region = "ord"

[build]
  dockerfile = "Dockerfile"

[env]
  FTDOSS_NODE_ID = "storage-1"
  FTDOSS_HTTP_PORT = "8080"
  FTDOSS_ZONE = "zone-1"
  FTDOSS_ADMIN_API_KEY = "dev-key"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    force_https = true
    handlers = ["http", "tls"]
    port = 443

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.http_checks]]
    interval = "10s"
    grace_period = "5s"
    method = "get"
    path = "/health"
    protocol = "http"
    timeout = "2s"
